#!/usr/bin/env bash
# Installing nginx my server
# nginx returns Hello World!  

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
