#!/usr/bin/env bash
# Install and config HAProxy

# Define HAProxy configuration
haproxy_config="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 530962-web-01 54.173.50.211:80 check
    server 530962-web-02 54.90.56.120:80 check
"

# Update packages and add HAProxy PPA
apt-get -y update && apt-get -y upgrade
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Install HAProxy
apt-get -y install haproxy

# Backup original HAProxy configuration
cp -a /etc/haproxy/haproxy.cfg{,.orig}

# Append custom configuration to HAProxy configuration file
echo "$haproxy_config" >> /etc/haproxy/haproxy.cfg

# Restart HAProxy service
service haproxy restart