#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

# Update Nginx configuration file to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
sudo systemctl restart nginx
