#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
#except the oth say "Hi"

number=0

while [ $number -lt 10 ] 
do
  if [ $number -eq 3 ]
  then
    echo "bad luck"
  elif [ $number -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( number++ ))
done