#!/usr/bin/env bash
# This script is displaying numbers except at 4, 9,17
#where id displays diff. sentences

number=1


while [ $number -lt 21 ] 
do
    echo $number
case $number in
    "4")
        echo "bad luck from China";;
    "9")
        echo "bad luck from Japan";;
    "17")
        echo "bad luck from Italy";;
esac
  (( number++ ))
done