#!/usr/bin/env bash
# This script is displaying a clock

hour=0

while [ $hour -lt 13 ] 
do
    echo "Hour: $hour"
    min=1
    while [ $min -lt 60 ]
    do
        echo "$min"
        (( min++ ))
    done
    (( hour++ ))
done