#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
#except the oth say "Hi"

hour=0

while [ $hour -lt 12 ] 
do
    echo "Hour: $hour"
    min=1
    while [ $min -lt 60 ]
    do
        echo "$min"
        (( min++ ))
    done
    (( hour++ ))
done