#!/usr/bin/env bash
# Configures an Ubuntu server as:
# localhost resolves into 127.0.0.2
# facebook.com resolves into 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/cpy_hosts
sed -i s/157.240.11.35/8.8.8.8/ ~/cpy_hosts
cp -f ~/hosts.new /etc/hosts